### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by daggr8** [nicksergeant/slacktapped#2]
Hi, 

Cant get it to work and i get this error in the log. Any ideas? Thanks!

2017-02-13T08:14:00.724584987Z app[web.1]: 08:14:00.723 [info]  [Processor] Running...
2017-02-13T08:14:01.552279951Z app[web.1]:
2017-02-13T08:14:01.552374189Z app[web.1]: 08:14:01.551 [error] Task #PID<0.11246.0> started from Quantum terminating
2017-02-13T08:14:01.552386630Z app[web.1]: ** (ArgumentError) the Access calls for keywords expect the key to be an atom, got: "checkins"
2017-02-13T08:14:01.552395166Z app[web.1]:     (elixir) lib/access.ex:166: Access.fetch/2
2017-02-13T08:14:01.552402577Z app[web.1]:     (elixir) lib/access.ex:179: Access.get/3
2017-02-13T08:14:01.552409396Z app[web.1]:     (elixir) lib/kernel.ex:1740: Kernel.get_in/2
2017-02-13T08:14:01.552416107Z app[web.1]:     (slacktapped) lib/slacktapped.ex:48: Slacktapped.main/0
2017-02-13T08:14:01.552422839Z app[web.1]:     (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
2017-02-13T08:14:01.552429752Z app[web.1]:     (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
2017-02-13T08:14:01.552436433Z app[web.1]:     (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2017-02-13T08:14:01.552443135Z app[web.1]: Function: &Quantum.Executor.execute/2
2017-02-13T08:14:01.552450234Z app[web.1]:     Args: [{"* * * * *", {Slacktapped, :main}, [], :utc}, %{d: {2017, 2, 13}, h: 8, jobs: [nil: %Quantum.Job{args: [], name: nil, nodes: [:nonode@nohost], overlap: true, pid: #PID<0.11240.0>, schedule: "* * * * *", state: :active, task: {Slacktapped, :main}, timezone: :utc}], m: 14, r: 0, w: 1}]

**Comment by nicksergeant** [comment]
Resolved on Slack.
